services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
      #Mount local AWS config as read-only for setup/ configs
      - ~/.aws:/root/.aws:ro
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      # to test/fix s3 still creating loop 
      - AWS_REGION
      # to test/fix s3 still creating loop
      - TF_WORKSPACE