# This workflow is triggered manually to destroy AWS resources in prod account.
name: Destroy

on:
  workflow_dispatch:
    inputs:
      workspace:
        type: choice
        description: Which AWS environment's resources should be destroyed?
        options:
          - staging
          - prod

permissions:
  id-token: write #Allows GitHub to issue an OIDC token
  contents: read #Allows GitHub to checkout code
                 #default permission when no permissions block is present

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Terraform workspace
        run: |
          echo "WORKSPACE=${{ github.event.inputs.workspace }}" >> $GITHUB_ENV

      # Chaining roles to the prod account
      - name: Assume the initial role in mgmt account using OIDC 
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.OIDC_GH_ACTIONS_ROLE_MGMT }}
          role-session-name: gh-actions-mgmt-${{ github.actor }}
          aws-region: us-east-1
          mask-aws-account-id: true
      - name: Assume the CI/CD Role in prod account
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.CICD_GH_ACTIONS_ROLE_PROD }}
          role-session-name: gh-actions-prod-${{ github.actor }}
          aws-region: us-east-1
          mask-aws-account-id: true
          role-chaining: true 

      - name: Terraform Destroy
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
            cd infra/
            docker compose run --rm terraform -chdir=deploy/ init   -input=false
            docker compose run --rm terraform -chdir=deploy/ workspace select -or-create "$WORKSPACE"
            docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve
